backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # HOME
  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  # DOCTORS
  - name: "doctors"
    label: "Profissionais"
    files:
      - file: "src/content/doctors.md"
        label: "Equipe Médica"
        name: "doctors"
        fields:
          - label: "Equipe"
            name: "doctors"
            widget: "list"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Especialidade", name: "role", widget: "string" }
              - { label: "Foto", name: "image", widget: "image" }
