backend:
  name: github
  repo: Aline12Lima/OralCare
  branch: main

media_folder: "content/uploads"
public_folder: "/content/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Texto", name: "body", widget: "markdown" }
